# ***Numpy***


- *A **NumPy array** (https://numpy.org) is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.*
- Some attributes of NumPy Array:
>- **ndim:** The number of dimensions, can be 1, 2, 3, ... N
>- **axis:** Each dimension is called an axis: `axis 0` is the vertical axis, goes from top to bottom, represents the number of rows, `axis 1` is the horizontal axis, goes from left to right, represents the number of columns, `axis 2` is the number of columns along z axis
>- **rank:** The number of axes is called the rank.
>- **shape:** It is a tuple whose length is the rank and elements are dimension of each axis.
>- **size:** It is the total number of elements, which is the product of all axis lengths.
>- **itemsize:** It gives you the size in bytes of each element of the array (depends on dtype).
>- **nbytes:** It gives you the total number of bytes occupied by entire array object in memory (size x itemsize).\

#### ***Creating Array***
- `np.array()`
- Empty 
- 0 D
- 1 D
- 2 D
- 3 D


In [11]:
import numpy as np

# creating empty array
arr1 = np.array([])
print("Array: ", arr1)
print("Type of array: ", type(arr1))
print("Dimensions: ", arr1.ndim)                # return the number of dimensions, an empty string means 1 dimensions
print("Shape: ", arr1.shape)                    # return a tuple shows shape of array
print("Size: ", arr1.size)                      # return the number of elements
print("Data Type: ", arr1.dtype)                # return the data type of array, default is float 64
print("Item Size in bytes: ", arr1.itemsize)    # return item size of each element in bytes, default is 8 for float 64
print("No of Bytes: ", arr1.nbytes)             # return the number of bytes of whole array
print("Array Data: ", arr1.data)                # return the array data
print("Array Strides: ", arr1.strides)          # return strides
print("Array Flag: ", arr1.flags)               # return the flags



Array:  []
Type of array:  <class 'numpy.ndarray'>
Dimensions:  1
Shape:  (0,)
Size:  0
Data Type:  float64
Item Size in bytes:  8
No of Bytes:  0
Array Data:  <memory at 0x7f5a95d03940>
Array Strides:  (8,)
Array Flag:    C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# creating 1-D array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

for i in range(3):
    for j in range(3):
        print(i,j)

arr3 = np.array([1,2,3,4,5])
list1 = [1,2,3,4,5]
arr3 = np.array(list1, dtype = np.uint8)
print("Array",arr3)

print("Array Dimensions: ", arr3.ndim)     
print("Array Shape: ", arr3.shape)                # it has 5 elements in one dimensional array 
print("Array Size: ", arr3.size)
print("Array Data Type: :", arr3.dtype)
print("Each Item Size:", arr3.itemsize)
print("Whole array size in bytes:", arr3.nbytes)
print("Array Data: ",arr3.data)
print("Array Strides: ", arr3.strides)            # jumps in bytes to move next element
print("Array Flags: ", arr3.flags)                # return the memory data

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
Array [1 2 3 4 5]
Array Dimensions:  1
Array Shape:  (5,)
Array Size:  5
Array Data Type: : uint8
Each Item Size: 1
Whole array size in bytes: 5
Array Data:  <memory at 0x7f5a7375d880>
Array Strides:  (1,)
Array Flags:    C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [48]:
# 2 D arrays

l1 = [
    [1,2,3],
    [4,5,6],
    [8,9,10]
]
arr4 = np.array(l1 , dtype = np.uint64)   
print("Array: ",arr4)
print("Dimensions: ", arr4.ndim)
print("Shape: ", arr4.shape)
print("Strides", arr4.strides)               # 24 bytes to move next row, and 8 bytes to move next coloum item
print("Size of array: ", arr4.size)          # return the number of elements, 3*3
print("Item Size in bytes: ", arr4.itemsize)
print("Whole array size in bytes: ", arr4.nbytes)
print("Print the flag: ", arr4.flags)
print("Array Data Type: ", arr4.dtype)

Array:  [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
Dimensions:  2
Shape:  (3, 3)
Strides (24, 8)
Size of array:  9
Item Size in bytes:  8
Whole array size in bytes:  72
Print the flag:    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Array Data Type:  uint64


In [67]:
# 3 D Arrays

l1 = [
    [[1,2,3,4],
     [3,4,5,6],
     [2,3,4,5],
     [4,5,6,7]],
    [[6,7,8,9],
     [4,5,6,7],
     [2,3,4,5],
     [5,6,7,8]],
    [[2,3,4,5],
     [3,4,5,6],
     [3,4,5,6],
     [5,6,7,8]],
]
arr5 = np.array(l1, dtype = np.uint64)

print("Array: ", arr5)
print("Array Shape: ", arr5.shape)         # no of layers , no of rows , no of columns
print("Dimensions:", arr5.ndim)
print("Size of array: ", arr5.size)        # no of layers * no of rows * no of columns
print("Each item size: ", arr5.itemsize)
print("Number of bytes:", arr5.nbytes)
print("Strides: ", arr5.strides)           # bytes to change layer, rows and columns
print("Memory Data:", arr5.data)
print("Memory Flag: ", arr5.flags)
print("Data Type:", arr5.dtype)

Array:  [[[1 2 3 4]
  [3 4 5 6]
  [2 3 4 5]
  [4 5 6 7]]

 [[6 7 8 9]
  [4 5 6 7]
  [2 3 4 5]
  [5 6 7 8]]

 [[2 3 4 5]
  [3 4 5 6]
  [3 4 5 6]
  [5 6 7 8]]]
Array Shape:  (3, 4, 4)
Dimensions: 3
Size of array:  48
Each item size:  8
Number of bytes: 384
Strides:  (128, 32, 8)
Memory Data: <memory at 0x7f5a8c039a90>
Memory Flag:    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Data Type: uint64


### `np.zeros` method

In [74]:
# creating 1 D array using zeros method
arr1 = np.zeros(5)
print (arr1)

# creating 2 D array using zeros method

arr2  = np.zeros((2,3))
print(arr2)

arr3 = np.zeros((3,2), dtype = np.uint16)
print(arr3)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]]


### `np.ones()` method

In [77]:
# creating 1 D array using ones method
arr1 = np.ones(4)
print(arr1)

# creating 2 D array using ones method
arr3 = np.ones((3,5), dtype=np.uint16)
print(arr3)

# creating 3 D array using ones method
arr2 = np.ones((2,3,4), dtype=np.uint8)
print(arr2)

[1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### `np.empty()` method
- this method creates junck values

In [87]:
# creating 1 D array using empty method
arr1 = np.empty(3)
print(arr1)

# creating 2 D array using empty method
arr3 = np.empty((2,5), dtype=np.uint16)
print(arr3)

# creating 3 D array using empty method
arr2 = np.empty((2,4,4), dtype=np.uint8)
print(arr2)

[7.74860419e-304 7.74860419e-304 7.74860419e-304]
[[10057     0     0     0     0]
 [    0     0     0    32     0]]
[[[  0   0   0   0]
  [  0   0 240  63]
  [  0   0   0   0]
  [  0   0 240  63]]

 [[  0   0   0   0]
  [  0   0 240  63]
  [  0   0   0   0]
  [  0   0 240  63]]]


### `np.full()` method
- first argument shows the shape of array
- second element shows element to be filled
- third argument shows data type

In [91]:
# creating 1 D array using full method
arr1 = np.full(3, 5, dtype = np.uint8)
print(arr1)

# creating 2 D array using full method
arr3 = np.full((2,5), 45, dtype=np.uint16)
print(arr3)

# creating 3 D array using full method
arr2 = np.full((2,4,4), 119, dtype=np.uint8)
print(arr2)

[5 5 5]
[[45 45 45 45 45]
 [45 45 45 45 45]]
[[[119 119 119 119]
  [119 119 119 119]
  [119 119 119 119]
  [119 119 119 119]]

 [[119 119 119 119]
  [119 119 119 119]
  [119 119 119 119]
  [119 119 119 119]]]


### `np.eye()` Method
This method is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

```
eye(N, M=None, k=0 , dtype=float)
```
- N: Number of rows in the output
- M: Number of columns in the output. If None, defaults to N
- k: Index of the diagonal: (Default 0) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
- dtype: Data-type of the returned array

In [95]:
# Creating an identical method with 3 rows and 4 columns 
arr1 = np.eye(3,4)
print(arr1)

# creating an identical method with 3 rows and 3 columns, 1 upper diagonal with int data type
arr2 = np.eye(3,3,1,dtype = np.uint8)
print(arr2)


# creating an identical method with 3 rows and 4 columns, 1 lower diagonal with int 64 
arr3 = np.eye(3,4,-1,dtype=np.uint64)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0 1 0]
 [0 0 1]
 [0 0 0]]
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]


### `np.arange()` Method

This function is used to get evenly spaced values within a given interval.

```
numpy.arange([start,] stop[, step])
```
- If only one argument is given will generate an int64 array from zero to that value (not inclusive)
- If two arguments are given then start value in inclusive, stop value is not inclusive and the default step is 1
- If three arguments are given then the third argument is the distance between two adjacent values. (default step size is 1)
- All the three arguments can be integers or floats


In [104]:
# creating an array from 1 to 3 equaly spaced with the interval of 1
arr1 = np.arange(3)
print(arr1)


# creating an array from 2 to 6 equally sapced interval of 1
arr2 = np.arange(2,6)
print(arr2)


# creating an array from 1 to 12 equally spaced with the interval of 2
arr3 = np.arange(1,12,2)
print(arr3)


# creating an array from 5 to 50 equally spaced with the interval of 2 and of data type int 64
arr4 = np.arange(5,50,2,dtype=np.uint64)
print(arr4)


# creating an array from 5 to 3 equally spaced with the interval of 2 and of data type int 64
arr5 = np.arange(5,3,2,dtype=np.uint64)
print(arr5)

[0 1 2]
[2 3 4 5]
[ 1  3  5  7  9 11]
[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
[]


###  `np.linspace()` Method

This method by default returns an array of 50 evenly spaced elements starting from the first argument (inclusive) to the second argument (inclusive). The third argument, if given, is the count of number of elements of the array, default is 50.

```
numpy.linspace(start, stop, num=50)
```

In [113]:
# creating an array from 3 to 4 equaly spaced into 50 elements
arr1 = np.linspace(3,4)
print(arr1)


# creating an array from 5 to 6 equally spaced into 50 elements
arr2 = np.linspace(5,4)
print(arr2)


# creating an array from 1 to 12 equally spaced into 2 elements
arr3 = np.linspace(1,12,2)
print(arr3)


# creating an array from 5 to 50 into 100 elemnts and of data type int 64
arr4 = np.linspace(5,50,100,dtype=np.uint64)
print(arr4)


[3.         3.02040816 3.04081633 3.06122449 3.08163265 3.10204082
 3.12244898 3.14285714 3.16326531 3.18367347 3.20408163 3.2244898
 3.24489796 3.26530612 3.28571429 3.30612245 3.32653061 3.34693878
 3.36734694 3.3877551  3.40816327 3.42857143 3.44897959 3.46938776
 3.48979592 3.51020408 3.53061224 3.55102041 3.57142857 3.59183673
 3.6122449  3.63265306 3.65306122 3.67346939 3.69387755 3.71428571
 3.73469388 3.75510204 3.7755102  3.79591837 3.81632653 3.83673469
 3.85714286 3.87755102 3.89795918 3.91836735 3.93877551 3.95918367
 3.97959184 4.        ]
[5.         4.97959184 4.95918367 4.93877551 4.91836735 4.89795918
 4.87755102 4.85714286 4.83673469 4.81632653 4.79591837 4.7755102
 4.75510204 4.73469388 4.71428571 4.69387755 4.67346939 4.65306122
 4.63265306 4.6122449  4.59183673 4.57142857 4.55102041 4.53061224
 4.51020408 4.48979592 4.46938776 4.44897959 4.42857143 4.40816327
 4.3877551  4.36734694 4.34693878 4.32653061 4.30612245 4.28571429
 4.26530612 4.24489796 4.2244898  4.2040

### `np.random.rand()` Method
- This method generates an array of random floats (between 0 and 1) of as many dimensions passed as argument.
- If no argument is passed, generates a scalar value between 0 and 1

In [125]:
# generate a random variable between 0 to 1, no argument is passed, scalar value will be generated
num = np.random.rand()
print(num)


# generate an array of five elements between 0 to 1
num = np.random.rand(5)
print(num)

# generate an array of five elements between 0 to 7
num = np.random.rand(5)*7
print(num)


# generate an 2 D array of shape(5*3) between 0 to 10 
num = np.random.rand(5*3)*10
print(num)


# Creating 3-D array of with random values using np.random.rand() from 0 to 20
arr = np.random.rand(5,4,3)*20
arr

0.008754589105756772
[0.86370833 0.28608951 0.86978083 0.77643596 0.67106691]
[4.11530485 2.44575385 2.19643431 6.42023158 1.0848113 ]
[7.31754193 8.69903439 4.29565174 2.31903206 9.52776678 2.86768005
 3.82121336 4.88819361 3.40686973 9.07885536 0.21364878 5.88003845
 5.43481605 6.92674964 4.16332911]


array([[[10.5546493 ,  5.14800992,  6.47704916],
        [10.08687643, 10.12202692,  3.07230012],
        [11.05634594,  2.68937067,  7.08889883],
        [ 8.68519924,  6.5559723 , 11.10656333]],

       [[ 3.92001268, 15.37298278, 17.10391548],
        [19.4028707 ,  9.87708776, 13.01427303],
        [19.62319842,  6.75291612, 16.26362341],
        [14.30311848, 11.40508593,  1.48222943]],

       [[16.82564205,  8.41188247, 16.22929553],
        [19.48153495,  6.57395111, 12.16987354],
        [ 2.44150645,  7.91024232, 19.84514119],
        [ 9.43200923, 14.28479082,  5.25072875]],

       [[ 3.26996421,  8.89123709,  0.51408345],
        [10.40745945, 19.66311352,  6.53004077],
        [15.48967599, 18.34240478,  0.52127959],
        [16.21764565,  3.53412307,  1.99908977]],

       [[19.75112626,  0.17217526, 10.3080097 ],
        [17.0964931 , 18.43077239, 13.21682553],
        [ 7.71034749,  3.46434145, 10.81502884],
        [19.07716895, 14.27438876, 15.41878948]]])

### `np.random.randint()` Method
This method returns an array of specified shape and fills it with random integers.
```
numpy.random.randint(low, high=None, size)
```
- low: Lowest (signed) integer to be drawn from the distribution. But, it works as a highest integer in the sample if high=None.
- high: Largest (signed) integer to be drawn from the distribution (not inclusive)
- size: number of samples to be generated (default is 1 for scalar and >1 for 1-D array and a tupple for ndarray)

In [132]:
# Generating a random integer scalar b/w interval (0,9) 
value = np.random.randint(10)
print(value)


# Generating a random integer scalar b/w interval (5,19) 
value = np.random.randint(low=5, high=20)
value


# creating 1-D array of size 6 of int type b/w interval (1,100) 
arr = np.random.randint(low=1, high=101, size=6)
arr

# By passing a tuple to size means rows and columns
arr = np.random.randint(low = 1, high = 10, size = (3,3))
arr


arr = np.random.randint(low = 1, high = 10, size = (2,3,4))
arr

2


array([[[2, 6, 5, 3],
        [7, 1, 7, 1],
        [3, 2, 7, 7]],

       [[5, 7, 2, 2],
        [3, 6, 6, 3],
        [1, 9, 5, 5]]])


###  `np.zeros_like()` Method
This method is used to get an array of zeros with the same shape and type as a given array.

```
zeros_like(arr, dtype=None) 
```

- arr: array like input
- dtype: Overrides the data type of the result

In [133]:
# creating a 2-D array
mylist = [[0, 1],[2, 3]]
arr1 = np.array(mylist)
print("A 2-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)

A 2-D array 
 [[0 1]
 [2 3]]

 Converted Array 
 [[0 0]
 [0 0]]
