## Scalar Math
#### ***First Method***

In [7]:
import numpy as np
# creating 1 D array having 4 random elements from 1 to 10 
arr1 = np.random.randint(1,10,size=4)
print(arr1)
# after the operations, a new ndarray is created
arr2 = arr1+2
print("After addition: ",arr2)
arr3 = arr1-2
print("After substraction: ",arr3)
arr4 = arr1*2
print("After multiplication: ",arr4)
arr5 = arr1/2
print("After division: ",arr5)
arr6 = arr1%2
print("After Mod operations: ",arr6)

[9 3 1 6]
After addition:  [11  5  3  8]
After substraction:  [ 7  1 -1  4]
After multiplication:  [18  6  2 12]
After division:  [4.5 1.5 0.5 3. ]
After Mod operations:  [1 1 1 0]


#### ***Second Method***

In [12]:
# scalar operations on 2 D arrays
arr1 = np.random.randint(1,10,size=(2,3))
print(arr1)
# after the operations, a new ndarray is created
arr2 = np.add(arr1,2)
print("After addition: ",arr2)
arr3 = np.subtract(arr1,2)
print("After substraction: ",arr3)
arr4 = np.multiply(arr1,2)
print("After multiplication: ",arr4)
arr5 = np.divide(arr1,2)
print("After division: ",arr5)
arr6 = np.mod(arr1,2)
print("After Mod operations: ",arr6)

[[7 4 9]
 [6 3 7]]
After addition:  [[ 9  6 11]
 [ 8  5  9]]
After substraction:  [[5 2 7]
 [4 1 5]]
After multiplication:  [[14  8 18]
 [12  6 14]]
After division:  [[3.5 2.  4.5]
 [3.  1.5 3.5]]
After Mod operations:  [[1 0 1]
 [0 1 1]]


### Arithmetic Operations on Arrays
#### ***First Method***

In [14]:
# scalar operations on 2 D arrays
arr1 = np.random.randint(1,10,size=(2,3))
arr2 = np.random.randint(11,20,size=(2,3))
print("Array1:" ,arr1)
print("Array2:", arr1)
# after the operations, a new ndarray is created
arrAdd = np.add(arr1,arr2)
print("After addition: ",arrAdd)
arrSub = np.subtract(arr1,arr2)
print("After substraction: ",arrSub)
arrMul = np.multiply(arr1,arr2)
print("After multiplication: ",arrMul)
arrDiv = np.divide(arr1,arr2)
print("After division: ",arrDiv)
arrMod = np.mod(arr1,arr2)
print("After Mod operations: ",arrMod)

Array1: [[5 3 5]
 [3 8 4]]
Array2: [[5 3 5]
 [3 8 4]]
After addition:  [[22 21 19]
 [20 21 23]]
After substraction:  [[-12 -15  -9]
 [-14  -5 -15]]
After multiplication:  [[ 85  54  70]
 [ 51 104  76]]
After division:  [[0.29411765 0.16666667 0.35714286]
 [0.17647059 0.61538462 0.21052632]]
After Mod operations:  [[5 3 5]
 [3 8 4]]


### ***Second Method***

In [20]:
# scalar operations on 1 D arrays
arr1 = np.random.randint(1,10,size=(4))
arr2 = np.random.randint(11,20,size=(4))
print("Array1:" ,arr1)
print("Array2:", arr2)
# after the operations, a new ndarray is created
arrAdd = arr1+arr2
print("After addition: ",arrAdd)
arrSub = arr1-arr2
print("After substraction: ",arrSub)
arrMul = arr1*arr2
print("After multiplication: ",arrMul)
arrDiv = arr1/arr2
print("After division: ",arrDiv)
arrMod = arr1%arr2
print("After Mod operations: ",arrMod)

Array1: [7 6 6 8]
Array2: [17 19 18 14]
After addition:  [24 25 24 22]
After substraction:  [-10 -13 -12  -6]
After multiplication:  [119 114 108 112]
After division:  [0.41176471 0.31578947 0.33333333 0.57142857]
After Mod operations:  [7 6 6 8]
