## Scalar Math
#### ***First Method***

In [7]:
import numpy as np
# creating 1 D array having 4 random elements from 1 to 10 
arr1 = np.random.randint(1,10,size=4)
print(arr1)
# after the operations, a new ndarray is created
arr2 = arr1+2
print("After addition: ",arr2)
arr3 = arr1-2
print("After substraction: ",arr3)
arr4 = arr1*2
print("After multiplication: ",arr4)
arr5 = arr1/2
print("After division: ",arr5)
arr6 = arr1%2
print("After Mod operations: ",arr6)

[9 3 1 6]
After addition:  [11  5  3  8]
After substraction:  [ 7  1 -1  4]
After multiplication:  [18  6  2 12]
After division:  [4.5 1.5 0.5 3. ]
After Mod operations:  [1 1 1 0]


#### ***Second Method***

In [12]:
# scalar operations on 2 D arrays
arr1 = np.random.randint(1,10,size=(2,3))
print(arr1)
# after the operations, a new ndarray is created
arr2 = np.add(arr1,2)
print("After addition: ",arr2)
arr3 = np.subtract(arr1,2)
print("After substraction: ",arr3)
arr4 = np.multiply(arr1,2)
print("After multiplication: ",arr4)
arr5 = np.divide(arr1,2)
print("After division: ",arr5)
arr6 = np.mod(arr1,2)
print("After Mod operations: ",arr6)

[[7 4 9]
 [6 3 7]]
After addition:  [[ 9  6 11]
 [ 8  5  9]]
After substraction:  [[5 2 7]
 [4 1 5]]
After multiplication:  [[14  8 18]
 [12  6 14]]
After division:  [[3.5 2.  4.5]
 [3.  1.5 3.5]]
After Mod operations:  [[1 0 1]
 [0 1 1]]


### Arithmetic Operations on Arrays
#### ***First Method***

In [14]:
# scalar operations on 2 D arrays
arr1 = np.random.randint(1,10,size=(2,3))
arr2 = np.random.randint(11,20,size=(2,3))
print("Array1:" ,arr1)
print("Array2:", arr1)
# after the operations, a new ndarray is created
arrAdd = np.add(arr1,arr2)
print("After addition: ",arrAdd)
arrSub = np.subtract(arr1,arr2)
print("After substraction: ",arrSub)
arrMul = np.multiply(arr1,arr2)
print("After multiplication: ",arrMul)
arrDiv = np.divide(arr1,arr2)
print("After division: ",arrDiv)
arrMod = np.mod(arr1,arr2)
print("After Mod operations: ",arrMod)

Array1: [[5 3 5]
 [3 8 4]]
Array2: [[5 3 5]
 [3 8 4]]
After addition:  [[22 21 19]
 [20 21 23]]
After substraction:  [[-12 -15  -9]
 [-14  -5 -15]]
After multiplication:  [[ 85  54  70]
 [ 51 104  76]]
After division:  [[0.29411765 0.16666667 0.35714286]
 [0.17647059 0.61538462 0.21052632]]
After Mod operations:  [[5 3 5]
 [3 8 4]]


### ***Second Method***

In [20]:
# scalar operations on 1 D arrays
arr1 = np.random.randint(1,10,size=(4))
arr2 = np.random.randint(11,20,size=(4))
print("Array1:" ,arr1)
print("Array2:", arr2)
# after the operations, a new ndarray is created
arrAdd = arr1+arr2
print("After addition: ",arrAdd)
arrSub = arr1-arr2
print("After substraction: ",arrSub)
arrMul = arr1*arr2
print("After multiplication: ",arrMul)
arrDiv = arr1/arr2
print("After division: ",arrDiv)
arrMod = arr1%arr2
print("After Mod operations: ",arrMod)

Array1: [7 6 6 8]
Array2: [17 19 18 14]
After addition:  [24 25 24 22]
After substraction:  [-10 -13 -12  -6]
After multiplication:  [119 114 108 112]
After division:  [0.41176471 0.31578947 0.33333333 0.57142857]
After Mod operations:  [7 6 6 8]


### ***Mathematical Operations***
##### ***1 D Array*** 

In [24]:
import numpy as np
# creating 1 D array of 5 elements of random floats between 0 and 10
arr1 = np.random.rand(5)*10
print("Actual Array: ", arr1)
absArr1 = np.abs(arr1)                      # this will return non negative numbers 
print("Absolute Values: ",absArr1)   
sqrArr1 = np.square(arr1)                   # this will return square of each element
print("Square: ",sqrArr1)   
sqrtArr1 = np.sqrt(arr1)                    # this will return square root of each element
print("Square Root: ",sqrtArr1)    
cbrtArr1 = np.cbrt(arr1)                    # this will return cube root of each element
print("Cube Root: ",cbrtArr1)   
logArr1 = np.log(arr1)                      # this will return log of each element
print("Log: ",logArr1) 
log2Arr1 = np.log2(arr1)                    # this will return log2 of each element
print("Log2: ",log2Arr1) 
log10Arr1 = np.log10(arr1)                  # this will return log10 of each element
print("Log10: ",log10Arr1) 
isnanArr1 = np.isnan(arr1)                  # this will return true of each element if value is nan else false
print("Is Nan: ",isnanArr1) 
ceilArr1 = np.ceil(arr1)                    # this will return ceil value of each element
print("Ceil: ",ceilArr1) 
floorArr1 = np.floor(arr1)                  # this will return floor value of each element
print("Floor: ",floorArr1) 
cumsumArr1 = np.cumsum(arr1)                  # this will return cumulative sum of all elements along the given axis
print("Cumsum: ",cumsumArr1) 

Actual Array:  [8.35556777 3.33691814 2.95914985 7.13540998 1.21516838]
Absolute Values:  [8.35556777 3.33691814 2.95914985 7.13540998 1.21516838]
Square:  [69.81551269 11.13502266  8.75656781 50.91407556  1.47663418]
Square Root:  [2.8905999  1.82672333 1.72021796 2.67121882 1.10234676]
Cube Root:  [2.02920219 1.49433689 1.4356734  1.92518725 1.06711728]
Log:  [2.12292811 1.20504767 1.08490201 1.96506971 0.19488265]
Log2:  [3.06273786 1.73851629 1.56518275 2.83499632 0.28115623]
Log10:  [0.92197597 0.52334555 0.47116696 0.85341893 0.08463646]
Is Nan:  [False False False False False]
Ceil:  [9. 4. 3. 8. 2.]
Floor:  [8. 3. 2. 7. 1.]
Cumsum:  [ 8.35556777 11.6924859  14.65163575 21.78704573 23.0022141 ]


##### ***2 D Array***

In [25]:
import numpy as np
# creating 1 D array of 5 elements of random floats between 0 and 10
arr1 = np.random.randint(-5,5,10)
print("Actual Array: ", arr1)
absArr1 = np.abs(arr1)                      # this will return non negative numbers 
print("Absolute Values: ",absArr1)   
sqrArr1 = np.square(arr1)                   # this will return square of each element
print("Square: ",sqrArr1)   
sqrtArr1 = np.sqrt(arr1)                    # this will return square root of each element
print("Square Root: ",sqrtArr1)    
cbrtArr1 = np.cbrt(arr1)                    # this will return cube root of each element
print("Cube Root: ",cbrtArr1)   
logArr1 = np.log(arr1)                      # this will return log of each element
print("Log: ",logArr1) 
log2Arr1 = np.log2(arr1)                    # this will return log2 of each element
print("Log2: ",log2Arr1) 
log10Arr1 = np.log10(arr1)                  # this will return log10 of each element
print("Log10: ",log10Arr1) 
isnanArr1 = np.isnan(arr1)                  # this will return true of each element if value is nan else false
print("Is Nan: ",isnanArr1) 
ceilArr1 = np.ceil(arr1)                    # this will return ceil value of each element
print("Ceil: ",ceilArr1) 
floorArr1 = np.floor(arr1)                  # this will return floor value of each element
print("Floor: ",floorArr1) 
cumsumArr1 = np.cumsum(arr1)                  # this will return cumulative sum of all elements along the given axis
print("Cumulative Sum: ",cumsumArr1) 

Actual Array:  [-2 -1 -4  4 -1 -4 -2 -4  0  0]
Absolute Values:  [2 1 4 4 1 4 2 4 0 0]
Square:  [ 4  1 16 16  1 16  4 16  0  0]
Square Root:  [nan nan nan  2. nan nan nan nan  0.  0.]
Cube Root:  [-1.25992105 -1.         -1.58740105  1.58740105 -1.         -1.58740105
 -1.25992105 -1.58740105  0.          0.        ]
Log:  [       nan        nan        nan 1.38629436        nan        nan
        nan        nan       -inf       -inf]
Log2:  [ nan  nan  nan   2.  nan  nan  nan  nan -inf -inf]
Log10:  [       nan        nan        nan 0.60205999        nan        nan
        nan        nan       -inf       -inf]
Is Nan:  [False False False False False False False False False False]
Ceil:  [-2. -1. -4.  4. -1. -4. -2. -4.  0.  0.]
Floor:  [-2. -1. -4.  4. -1. -4. -2. -4.  0.  0.]
Cumulative Sum:  [ -2  -3  -7  -3  -4  -8 -10 -14 -14 -14]


C:\Users\muhammad.iqbal\AppData\Local\Temp\ipykernel_11772\3355799235.py:9: RuntimeWarning: invalid value encountered in sqrt
  sqrtArr1 = np.sqrt(arr1)                    # this will return square root of each element
C:\Users\muhammad.iqbal\AppData\Local\Temp\ipykernel_11772\3355799235.py:13: RuntimeWarning: divide by zero encountered in log
  logArr1 = np.log(arr1)                      # this will return log of each element
C:\Users\muhammad.iqbal\AppData\Local\Temp\ipykernel_11772\3355799235.py:13: RuntimeWarning: invalid value encountered in log
  logArr1 = np.log(arr1)                      # this will return log of each element
C:\Users\muhammad.iqbal\AppData\Local\Temp\ipykernel_11772\3355799235.py:15: RuntimeWarning: divide by zero encountered in log2
  log2Arr1 = np.log2(arr1)                    # this will return log2 of each element
C:\Users\muhammad.iqbal\AppData\Local\Temp\ipykernel_11772\3355799235.py:15: RuntimeWarning: invalid value encountered in log2
  log2Arr1 = np.l

### ***Aggregate Functions***
##### ***1 D Array***

In [38]:
arr1 = np.random.randint(5,10, size=10)
print(arr1)
arr1Min = np.min(arr1)
print("Min Value: ", arr1Min)
arr1Max = np.max(arr1)
print("Max Value: ", arr1Max)
arr1Sum = np.sum(arr1)
print("Sum Value: ", arr1Sum)
arr1Pro = np.prod(arr1)                         # return product over the given axis
print("Product Value: ", arr1Pro)  
arr1Mean = np.mean(arr1)                        # return mean over the given axis
print("Mean: ", arr1Mean)  
arr1Avg = np.average(arr1)                      # return average over the given axis
print("Average: ", arr1Avg)    
arr1Median = np.median(arr1)                    # return median over the given axis
print("Median: ", arr1Median)  
arr1Variance = np.var(arr1)                     # return variance over the given axis, how each point id differ from mean
print("Variance: ", arr1Variance)
arr1Std = np.std(arr1)                          # return standard deviation over the given axis
print("Standar Deviation: ", arr1Std)  
arr1Std = np.std(arr1)                          # return standard deviation over the given axis
print("Standar Deviation: ", arr1Std)
arr1Per100 = np.percentile(arr1,100)            # return percentile  100
print("Percentile100: ", arr1Per100)      
arr1Per0 = np.percentile(arr1,0)                # return percentile 0
print("Percentile0: ", arr1Per0)  

[8 8 7 9 6 8 9 5 9 6]
Min Value:  5
Max Value:  9
Sum Value:  75
Product Value:  470292480
Mean:  7.5
Average:  7.5
Median:  8.0
Variance:  1.85
Standar Deviation:  1.3601470508735443
Standar Deviation:  1.3601470508735443
Percentile100:  9.0
Percentile0:  5.0


##### `***Next topic see from original files as my files deleted in hurry***`